---
title       : Lego Dataset Explorer  
subtitle    : Coursera - DDP Project
author      : Stefan papp
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Logo Set Explorer

With this The Lego Set Explorer, we visualize LEGO Sets. The LEGO Set consists of Lego pieces until 2016.

The dataset is from [Rebrickable.com](http://rebrickable.com/). It contains the basic information of each set (set id, year, number of pieces, theme, set name).  

Data Source: http://rebrickable.com/downloads 

--- .class #id 

## Server 
```{r}
#########
# Author: Stefan Papp
#########

library(shiny)
source("data_processing.R")
source("helper_function.R")

themes <- sort(unique(data$theme))

shinyServer(
  function(input, output) {
    output$setid <- renderText({input$setid})

    # Initialize reactive values
    values <- reactiveValues()
    values$themes <- themes
    
    # Create event type checkbox
    output$themesControl <- renderUI({
        checkboxGroupInput('themes', 'LEGO Themes:', 
                           themes, selected = values$themes)
    })
    
    # Add observer on select-all button
    observe({
        if(input$selectAll == 0) return()
        values$themes <- themes
    })
    
    # Add observer on clear-all button
    observe({
        if(input$clearAll == 0) return()
        values$themes <- c() # empty list
    })

    # Prepare dataset
    dataTable <- reactive({
        groupByTheme(data, input$timeline[1], 
                     input$timeline[2], input$pieces[1],
                     input$pieces[2], input$themes)
    })

    dataTableBySetYear <- reactive({
        groupByYearSet(data, input$timeline[1], 
                       input$timeline[2], input$pieces[1],
                       input$pieces[2], input$themes)
    })

    dataTableByYear <- reactive({
        groupByYearAgg(data, input$timeline[1], 
                    input$timeline[2], input$pieces[1],
                    input$pieces[2], input$themes)
    })

    dataTableByPiece <- reactive({
        groupByYearAll(data, input$timeline[1], 
                       input$timeline[2], input$pieces[1],
                       input$pieces[2], input$themes)
    })

    dataTableByPieceAvg <- reactive({
        groupByPieceAvg(data, input$timeline[1], 
                        input$timeline[2], input$pieces[1],
                        input$pieces[2], input$themes)
    })

    dataTableByPieceThemeAvg <- reactive({
        groupByPieceThemeAvg(data, input$timeline[1], 
                             input$timeline[2], input$pieces[1],
                             input$pieces[2], input$themes)
    })
    
    # Render data table
    output$dTable <- renderDataTable({
        dataTable()
    } 
    )
    
    output$setsByYear <- renderChart({
        plotSetsCountByYear(dataTableBySetYear())
    })

    output$themesByYear <- renderChart({
        plotThemesCountByYear(dataTableByYear())
    })

    output$piecesByYear <- renderChart({
        plotPiecesByYear(dataTableByPiece())
    })

    output$piecesByYearAvg <- renderChart({
        plotPiecesByYearAvg(dataTableByPieceAvg())
    })

    output$piecesByThemeAvg <- renderChart({
        plotPiecesByThemeAvg(dataTableByPieceThemeAvg())
    })
    
  } 
)
```


--- .class #id 

## UI 
```{r}
shinyUI(
    navbarPage("LEGO Set Explorer", 

    # multi-page user-interface with navigation bar.
        tabPanel("Data Exploration",
             sidebarPanel(
                sliderInput("timeline", 
                            "Timeline:", 
                            min = 1950,
                            max = 2016,
                            value = c(2000, 2016)
                            ),
                
                sliderInput("pieces", 
                            "Contains Number of Pieces:",
                            min = -1,
                            max = 5922,
                            value = c(250, 666)  
                            ),
                
                actionButton(inputId = "selectAll", 
                             label = "Select All",
                             icon = icon("check-square-o")),
                             
                actionButton(inputId = "clearAll", 
                             label = "Clear Selection", 
                             icon = icon("square-o")),
                
                uiOutput("themesControl")
             ),
             
             mainPanel(
                 tabsetPanel(
           
                   tabPanel(p(icon("table"), "Dataset"),
                            dataTableOutput(outputId="dTable")
                   ), 
                   
                   tabPanel(p(icon("line-chart"), "Data Visualization"),
                            h4('Number of Sets by Year', align = "center"),
                            h5('Hover over each point for Year and Total Number of Sets.', align ="center"),
                            showOutput("setsByYear", "nvd3"),
                            h4('Number of Themes by Year', align = "center"),
                            h5('Hover over each bar for Year and Total Number of Themes.', align ="center"),
                            showOutput("themesByYear", "nvd3"),
                            h4('Number of Pieces by Year', align = "center"),
                            h5('Hover over each point for Set Name, ID and Theme.', align ="center"),
                            showOutput("piecesByYear", "nvd3"),
                            h4('Number of Average Pieces by Year', align = "center"),
                            showOutput("piecesByYearAvg", "nvd3"),
                            h4('Number of Average Pieces by Theme', align = "center"),
                            showOutput("piecesByThemeAvg", "nvd3")
                   )
                 )
            )     
        ), 

```


--- .class #id 
## Other
```{r}
require(data.table)

library(dplyr)
library(DT)
library(rCharts)

## Helper functions

#' Aggregate dataset by year, piece and theme
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @param minPiece
#' @param maxPiece
#' @param themes
#' @return data.table
#'
groupByYearAll <- function(dt, minYear, maxYear, minPiece,
                             maxPiece, themes) {
    result <- dt %>% filter(year >= minYear, year <= maxYear,
                            pieces >= minPiece, pieces <= maxPiece,
                            theme %in% themes) 
    return(result)
}

#' Aggregate dataset only by year
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @return data.table
#'
groupByYear <- function(dt, minYear, maxYear) {
    result <- dt %>% filter(year >= minYear, year <= maxYear) 
    return(result)
}

#' Aggregate dataset by sets
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @param minPiece
#' @param maxPiece
#' @param themes
#' @return result data.table
#' 
groupByYearSet <- function(dt, minYear, maxYear, 
                           minPiece, maxPiece, themes) {
    dt <- groupByYear(dt, minYear, maxYear)
    result <- dt %>% 
        group_by(year) %>% 
        summarise(total_sets = n_distinct(setId)) %>%
        arrange(year)
    return(result) 
}

#' Aggregate dataset by themes
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @param minPiece
#' @param maxPiece
#' @param themes
#' @return result data.table
#' 
groupByTheme <- function(dt, minYear, maxYear, 
                         minPiece, maxPiece, themes) {
    # use pipelining
    dt <- groupByYearAll(dt, minYear, maxYear, minPiece,
                           maxPiece, themes) 
    result <- datatable(dt, options = list(iDisplayLength = 50))
    return(result)
    # The following does not work
    #     fn$sqldf("SELECT * FROM data 
    #          WHERE year >= $minYear and year <= $maxYear
    #          and theme in $themes")

    #return(data.table(result))
}

#' Aggregate dataset by year to get total count of themes
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @param minPiece
#' @param maxPiece
#' @param themes
#' @return data.table 2 columns
#'
groupByYearAgg <- function(dt, minYear, maxYear, minPiece,
                           maxPiece, themes) {
    # only need the minYear and maxYear here
    dt <- groupByYear(dt, minYear, maxYear)
    result <- dt %>% 
            group_by(year)  %>% 
            summarise(count = n_distinct(theme)) %>%
            arrange(year)
    return(result)
}

#' Aggregate dataset by year to get total count of average
#' number of pieces
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @param minPiece
#' @param maxPiece
#' @param themes
#' @return data.table 2 columns
#'
groupByPieceAvg <- function(dt,  minYear, maxYear, minPiece,
                            maxPiece, themes) {
    dt <- groupByYearAll(dt, minYear, maxYear, minPiece,
                           maxPiece, themes)
    result <- dt %>% 
            group_by(year) %>% 
            summarise(avg = mean(pieces)) %>%
            arrange(year)
    return(result)      
}

#' Average pieces for each theme
#' 
#' @param dt data.table
#' @param minYear
#' @param maxYear
#' @param minPiece
#' @param maxPiece
#' @param themes
#' @return data.table 2 columns
#'
groupByPieceThemeAvg <- function(dt,  minYear, maxYear, minPiece,
                                 maxPiece, themes) {
    dt <- groupByYearAll(dt, minYear, maxYear, minPiece,
                           maxPiece, themes)
    result <- dt %>% 
            group_by(theme) %>%
            summarise(avgPieces = mean(pieces)) %>%
            arrange(theme)
    return(result)
}

#' Plot number of sets by year
#' 
#' @param dt data.table
#' @param dom
#' @param xAxisLabel year
#' @param yAxisLabel number of sets
#' @return setsByYear plot
plotSetsCountByYear <- function(dt, dom = "setsByYear", 
                                    xAxisLabel = "Year",
                                    yAxisLabel = "Number of Sets") {
        setsByYear <- nPlot(
            total_sets ~ year,
            data = dt,
            type = "stackedAreaChart",
            dom = dom, width = 650
        )
        setsByYear$chart(margin = list(left = 100))
        setsByYear$chart(color = c('purple', 'blue', 'green'))
        setsByYear$chart(tooltipContent = "#! function(key, x, y, e){ 
  return '<h5><b>Year</b>: ' + e.point.year + '<br>' + '<b>Total Sets</b>: ' 
    + e.point.total_sets + '<br>'
    + '</h5>'
} !#")
        setsByYear$yAxis(axisLabel = yAxisLabel, width = 80)
        setsByYear$xAxis(axisLabel = xAxisLabel, width = 70)
        setsByYear 
}

#' Plot number of themes by year
#' 
#' @param dt data.table
#' @param dom
#' @param xAxisLabel year
#' @param yAxisLabel number of themes
#' @return themesByYear plot
plotThemesCountByYear <- function(dt, dom = "themesByYear", 
                                  xAxisLabel = "Year",
                                  yAxisLabel = "Number of Themes") {
    themesByYear <- nPlot(
        count ~ year,
        data = dt,
        type = "multiBarChart",
        dom = dom, width = 650
    )
    themesByYear$chart(margin = list(left = 100))
    themesByYear$yAxis(axisLabel = yAxisLabel, width = 80)
    themesByYear$xAxis(axisLabel = xAxisLabel, width = 70)
    themesByYear$chart(tooltipContent = "#! function(key, x, y, e){ 
  return '<h5><b>Year</b>: ' + e.point.year + '<br>' + '<b>Total Themes</b>: ' + e.point.count + '<br>'
    + '</h5>'
} !#")
    themesByYear
}

#' Plot number of pieces by year
#' 
#' @param dt data.table
#' @param dom
#' @param xAxisLabel year
#' @param yAxisLabel number of pieces
#' @return plotPiecesByYear plot
plotPiecesByYear <- function(dt, dom = "piecesByYear", 
                             xAxisLabel = "Year", 
                             yAxisLabel = "Number of Pieces") {
    piecesByYear <- nPlot(
        pieces ~ year,
        data = dt,
        type = "scatterChart",
        dom = dom, width = 650
    )
    piecesByYear$chart(margin = list(left = 100), 
                       showDistX = TRUE,
                       showDistY = TRUE)
    piecesByYear$chart(color = c('green', 'orange', 'blue'))
    piecesByYear$chart(tooltipContent = "#! function(key, x, y, e){ 
  return '<h5><b>Set Name</b>: ' + e.point.name + '<br>'
    + '<b>Set ID</b>: ' + e.point.setId + '<br>'
    + '<b>Theme</b>: ' + e.point.theme
    + '</h5>'
} !#")
    piecesByYear$yAxis(axisLabel = yAxisLabel, width = 80)
    piecesByYear$xAxis(axisLabel = xAxisLabel, width = 70)
    #     piecesByYear$chart(useInteractiveGuideline = TRUE)
    piecesByYear
}

#' Plot number of average pieces by year
#' 
#' @param dt data.table
#' @param dom
#' @param xAxisLabel year
#' @param yAxisLabel number of pieces
#' @return themesByYear plot
plotPiecesByYearAvg <- function(dt, dom = "piecesByYearAvg", 
                             xAxisLabel = "Year",
                             yAxisLabel = "Number of Pieces") {

    piecesByYearAvg <- nPlot(
        avg ~ year,
        data = dt,
        type = "lineChart",
        dom = dom, width = 650
    )
    piecesByYearAvg$chart(margin = list(left = 100))
    piecesByYearAvg$chart(color = c('orange', 'blue', 'green'))
    piecesByYearAvg$yAxis(axisLabel = yAxisLabel, width = 80)
    piecesByYearAvg$xAxis(axisLabel = xAxisLabel, width = 70)
    piecesByYearAvg
}

#' Plot number of average pieces by theme
#' 
#' @param dt data.table
#' @param dom
#' @param xAxisLabel theme
#' @param yAxisLabel number of pieces
#' @return piecesByThemeAvg plot
plotPiecesByThemeAvg <- function(dt, dom = "piecesByThemeAvg", 
                                 xAxisLabel = "Themes", 
                                 yAxisLabel = "Number of Pieces") {
    piecesByThemeAvg <- nPlot(
        avgPieces ~ theme,
        data = dt,
        type = "multiBarChart",
        dom = dom, width = 650
    )
    piecesByThemeAvg$chart(margin = list(left = 100))
    piecesByThemeAvg$chart(color = c('pink', 'blue', 'green'))
    piecesByThemeAvg$yAxis(axisLabel = yAxisLabel, width = 80)
    piecesByThemeAvg$xAxis(axisLabel = xAxisLabel, width = 200,
                           rotateLabels = -20, height = 200)
    piecesByThemeAvg
}

```


--- .class #id 
## Summary
```{r}

```


--- .class #id 
